[[links]]
name = "GitHub"
url = "https://github.com/minahermina"

[[links]]
name = "regexr"
url = "https://regexr.com/"

[[links]]
name = "C libraries"
url = "https://ccodearchive.net/list.html"

[[links]]
name = "UniKraft"
url = "unikraft.org"

[[links]]
name = "Tldr Legal"
url = "https://www.tldrlegal.com/"

[[links]]
name = "Ffmpeg irc"
url = "https://web.libera.chat/"

[[links]]
name = "free-for.dev"
url = "https://free-for.dev/#/"


[[links]]
name = "Void Linux"
url = "https://voidlinux.org/"

[[links]]
name = "AWS Academy"
url = "https://awsacademy.instructure.com/"

[[links]]
name = "Graduation Project"
url = "https://github.com/AbdelrahmanMohamed16/Graduation_Project"

[[links]]
name = "Figma"
url = "https://www.figma.com/"

[[links]]
name = "FCAI 2025"
url = "https://drive.google.com/drive/folders/1Uxp6obAt3XfiH5fhWH6xCYlowoGLEbjr"

[[links]]
name = "Cambridge Dictionary"
url = "https://dictionary.cambridge.org/"

[[links]]
name = "FCAI 2024"
url = "https://drive.google.com/drive/folders/1NYML3S8egAWuWJ51NufeDnM4GPOdAZaL"

[[links]]
name = "Google Classroom"
url = "https://classroom.google.com/"

[[links]]
name = "Cdecl"
url = "https://cdecl.org/"

[[links]]
name = "Draw IO"
url = "https://draw.io"

[[links]]
name = "Miro "
url = "https://miro.com/app/dashboard/"

[[links]]
name = "Google Drive"
url = "https://drive.google.com/"

[[links]]
name = "Youtube"
url = "https://www.youtube.com/"

[[links]]
name = "Dotfiles"
url = "https://github.com/minahermina/dotfiles"

[[links]]
name = "YTS"
url = "https://yts.mx/"

[[links]]
name = "Bing"
url = "https://www.bing.com/"

[[links]]
name = "IBM Dynamic Libraries"
url = "https://developer.ibm.com/tutorials/l-dynamic-libraries/"

[[links]]
name = "Beautiful"
url = "https://www.beautiful.ai/"

[[links]]
name = "Roadmap"
url = "https://roadmap.sh/ "

[[links]]
name = "Roadmap"
url = "https://roadmap.sh/"

[[links]]
name = "PFPMaker"
url = "https://pfpmaker.com/"

[[links]]
name = "MotionElements"
url = "https://www.motionelements.com"

[[links]]
name = "FlowGPT"
url = "https://flowgpt.com/"

[[links]]
name = "Krisp"
url = "https://krisp.ai/"

[[links]]
name = "Beatoven AI"
url = "https://www.beatoven.ai/"

[[links]]
name = "Flair AI"
url = "https://flair.ai/"

[[links]]
name = "Illustroke AI"
url = "https://illustroke.com/"

[[links]]
name = "StockImg"
url = "https://stockimg.ai/"

[[links]]
name = "Copy AI"
url = "https://www.copy.ai/"

[[links]]
name = "Dictation AI"
url = "https://dictation.io/"

[[links]]
name = "Mozilla Web Docs"
url = "https://developer.mozilla.org/en-US/"

[[links]]
name = "Kaiber"
url = "https://kaiber.ai/"

[[links]]
name = "Humata AI"
url = "https://www.humata.ai/"

[[links]]
name = "Tome"
url = "https://tome.app/"

[[links]]
name = "Slides AI"
url = "https://www.slidesai.io/"

[[links]]
name = "Shotstash"
url = "https://shotstash.com/"

[[links]]
name = "Data to Viz"
url = "https://www.data-to-viz.com/"

[[links]]
name = "DataViz Project"
url = "https://datavizproject.com/"

[[links]]
name = "Learn Python"
url = "https://www.learnpython.org/"

[[links]]
name = "LeetCode"
url = "https://leetcode.com/"

[[links]]
name = "Vjudge"
url = "https://vjudge.net/group/l2-c2-uni-spring23-phase1"

[[links]]
name = "Eng Hammad Recommendations"
url = "https://github.com/Eyadhamza/Eng-Hammad-Recommendations"

[[links]]
name = "Gamma AI"
url = "https://gamma.app/"

[[links]]
name = "Scratch"
url = "https://scratch.mit.edu/"

[[links]]
name = "MyCima"
url = "https://wecima.movie/"

[[links]]
name = "arXiv - Papers"
url = "https://arxiv.org/"

[[links]]
name = "Kernel Newbies"
url = "https://kernelnewbies.org/?utm_source=devglan"

[[links]]
name = "Cybrary"
url = "https://www.cybrary.it/"

[[links]]
name = "TLDP Guides"
url = "https://tldp.org/guides.html"

[[links]]
name = "Linux Opsys"
url = "https://linuxopsys.com/"

[[links]]
name = "Gmail"
url = "https://mail.google.com/mail/u/0/"


[[links]]
name = "Linux Inside Booting"
url = "https://0xax.gitbooks.io/linux-insides/content/Booting/linux-bootstrap-1.html"

[[links]]
name = "KOCW Document"
url = "http://contents.kocw.net/KOCW/document/2014/Yeungnam/KWAKJongwook/111.pdf"

[[links]]
name = "Outlier"
url = "https://app.outlier.ai/en/expert"

[[links]]
name = "Twitter"
url = "https://twitter.com/home?lang=en"

[[links]]
name = "NetAcad"
url = "https://www.netacad.com/portal/learning"

[[links]]
name = "Skills for All"
url = "https://skillsforall.com/launch?id=ec0847b7-e6fc-4597-bc31-38ddd6b07a2f&tab=curriculum&view=e4438117-81a5-5b37-81a5-dc26c153963d"

[[links]]
name = "Discord"
url = "https://discord.com/channels/@me"

[[links]]
name = "3askrya"
url = "https://miltraining.cu.edu.eg/Student/CourseRegistration/1"

[[links]]
name = "Whatsapp"
url = "https://web.whatsapp.com/"

[[links]]
name = "LinkedIn"
url = "https://www.linkedin.com/"

[[links]]
name = "Facebook"
url = "https://www.facebook.com/"

[[links]]
name = "Telegram Web"
url = "https://web.telegram.org/a/"

[[links]]
name = "Quora"
url = "https://www.quora.com/"

[[links]]
name = "Twitter"
url = "https://twitter.com/home?lang=en"

[[links]]
name = "Animelek"
url = "https://animelek.me/"

[[links]]
name = "Learn to Play Go"
url = "https://online-go.com/learn-to-play-go"

[[links]]
name = "Oxford Learner's Dictionaries"
url = "https://www.oxfordlearnersdictionaries.com/definition/english/"

[[links]]
name = "SVG Repo"
url = "https://www.svgrepo.com/collections/filled/"

[[links]]
name = "Loader.to"
url = "https://loader.to/en28/1080p-video-downloader.html"

[[links]]
name = "SlidesGo"
url = "https://slidesgo.com/"

[[links]]
name = "RDI Tashkeel"
url = "https://rdi-tashkeel.com/en/home"

[[links]]
name = "1Lib"
url = "https://eg1lib.org/s/?q=C%2B%2B"

[[links]]
name = "Beulr"
url = "https://www.beulr.com/"

[[links]]
name = "Origastock"
url = "https://www.origastock.com/fonts/arabic-fonts-1.html"

[[links]]
name = "RTL Styling"
url = "https://rtlstyling.com/posts/rtl-styling"

[[links]]
name = "CopyKat"
url = "https://copykat.com/"

[[links]]
name = "Hemingway App"
url = "https://hemingwayapp.com/"

[[links]]
name = "JSON Crack"
url = "https://jsoncrack.com/"

[[links]]
name = "Library Genesis"
url = "https://www.libgen.rs/"

[[links]]
name = "C Utils Library"
url = "https://github.com/barrust/c-utils?tab=readme-ov-file"

[[links]]
name = "Reuters"
url = "https://www.reuters.com/"
