[[repos]]
name = "Graduation Project"
url = "https://github.com/AbdelrahmanMohamed16/Graduation_Project"

[[repos]]
name = "Arabic-NLP-Dataset"
url = "https://github.com/minahermina/Arabic-NLP-Dataset"

[[repos]]
name = "awesome-github-profile-readme-templates"
url = "https://github.com/minahermina/awesome-github-profile-readme-templates"

[[repos]]
name = "BigDecimalInt"
url = "https://github.com/minahermina/BigDecimalInt"

[[repos]]
name = "BigReal"
url = "https://github.com/minahermina/BigReal"

[[repos]]
name = "Computer-Graphics-Algorithms"
url = "https://github.com/minahermina/Computer-Graphics-Algorithms"

[[repos]]
name = "Data-Compression-Algorithms-using-Java"
url = "https://github.com/minahermina/Data-Compression-Algorithms-using-Java"

[[repos]]
name = "Data-Structures"
url = "https://github.com/minahermina/Data-Structures"

[[repos]]
name = "Digital-Signals-Processing"
url = "https://github.com/minahermina/Digital-Signals-Processing"

[[repos]]
name = "dotfiles"
url = "https://gitlab.com/minahermina/dotfiles"

[[repos]]
name = "Higher-Studies-System"
url = "https://github.com/minahermina/Higher-Studies-System"

[[repos]]
name = "imglib"
url = "https://github.com/minahermina/imglib"

[[repos]]
name = "linux-notes"
url = "https://github.com/minahermina/linux-notes"

[[repos]]
name = "minaalbert33"
url = "https://github.com/minahermina/minaalbert33"

[[repos]]
name = "missing-with-linux-kernel-modules"
url = "https://github.com/minahermina/missing-with-linux-kernel-modules"

[[repos]]
name = "OpenGL-Project"
url = "https://github.com/minahermina/OpenGL-Project"

[[repos]]
name = "Security-Algorithms"
url = "https://github.com/minahermina/Security-Algorithms"

[[repos]]
name = "Simple-Unix-Shell"
url = "https://github.com/minahermina/Simple-Unix-Shell"

[[repos]]
name = "xv6-riscv"
url = "https://github.com/minahermina/xv6-riscv"

[[repos]]
name = "resume"
url = "https://github.com/minahermina/resume.git"

[[repos]]
name = "minahermina.gitub.io"
url = "https://github.com/minahermina/minahermina.github.io"

[[repos]]
name = "Kernel-Config-with-lockdep-module"
url = "https://github.com/minahermina/Kernel-Config-with-lockdep-module"

[[repos]]
name = "Linux-Programming-Interface-Journey"
url = "https://github.com/minahermina/Linux-Programming-Interface-Journey"

[[repos]]
name = "Cairo Website Main"
url = "https://github.com/moazadly/cairo_dictionary_main"

[[repos]]
name = "Machine Vision"
url = "https://github.com/minahermina/machine-vision"
