# vim: filetype=sh
dbus-update-activation-environment --all &
setxkbmap -layout us,ara -variant ,digits -option grp:ctrl_space_toggle caps:escape
xmodmap $XDG_CONFIG_HOME/xmodmap/Xmodmap
sxhkd &
ofh &
xsetroot -solid "#070707"
xset r rate 200 30 &
xset b off &
clipmenud &
dwmblocks &
eval $(gpg-agent --daemon)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export GPG_TTY=$(tty)
xrandr --output HDMI-0 --mode 2560x1440 --rate 144
dwm
