#!/bin/python3

import toml
import os

def run_dmenu(args, prompt, lines=0):
    cmd = f'echo "{args}" | dmenu -i -p "{prompt}" '
    if lines > 0 :
        cmd += f'-l {lines}'
    print(cmd)
    return os.popen(cmd).read().strip()

def move2_tagN(N):
    cmd = f'xdotool key $MAINMOD+2'
    os.popen(cmd).read().strip()

def run_cmd(cmd):
    os.popen(cmd).read().strip()

def main():

    # Loading the repos file
    XDG_DATA_HOME = os.path.expandvars("$XDG_DATA_HOME")
    file_path = os.path.expanduser(f'{XDG_DATA_HOME}/bookmarks.toml')
    data = toml.load(file_path)

    links_dict = {link['name']: link['url'] for link in data['links']}

    keys = list(links_dict.keys())

    keys_string = '\n'.join(keys)
    browser = os.environ['BROWSER']

    dmenu_command = f'echo "{keys_string}" | dmenu -i -l 10 -p "Bookmarks"'
    dmenu_command = f'echo "{keys_string}" | dmenu -i -l 10 -p "Bookmarks"'
    choice = os.popen(dmenu_command).read().strip()
    move2_tag2 = 'xdotool key $MAINMOD+2'

    if choice in links_dict:
        selected_url = links_dict[choice]
        os.system(f'{browser} {selected_url} && {move2_tag2}')
    elif choice == '+1':
        name = run_dmenu("", "Enter bookmark name:")
        url = run_dmenu("", "Enter bookmark link:")
        if name and url:
            with open(file_path, "a") as file:
                file.write(f'[[links]]\nname = "{name}"\nurl = "{url}"\n')
    elif len(choice) > 1:
        os.system(f'{browser} https://www.google.com/search?q="{choice}" && {move2_tag2}')
    else: 
        exit()

if __name__ == '__main__':
    main()
